In [1]:
import sys
import os
import pandas as pd

sys.path.append('c:\\Users\\andres\\Desktop\\SEPTIMO SEMESTRE\\MONITORIA\\analisis')

import connection as conn

co=conn.connect()

In [ ]:


res_tab=pd.read_sql("""
                    SELECT *
                    FROM response_response as r
                    JOIN visit_visit as v
                    ON r.visita_id=v.id
                    JOIN surveysession_surveysession as sv
                    ON v.surveysession_id=sv.id
                    JOIN observer_observer as o
                    ON sv.observer_id=o.id
                    JOIN question_question as q
                    ON r.question_id=q.id
                    WHERE o.email='andres.david.ortega@correounivalle.edu.co'
                    
                    
""",co)

In [36]:
A_question_res=pd.read_sql("""
                           
                         
                           

                        SELECT * 
                        FROM response_response as r
                        JOIN question_question as q
                        ON r.question_id=q.id
                        JOIN subcategory_subcategory as sub
                        ON q.subcategory_id=sub.id
                        JOIN category_category as ca
                        ON sub.category_id=ca.id
                        WHERE sub.name='Fumador Activo'
                        AND ca.name='Factores Socioculturales'
                        AND q.parent_question_id IN (
                           
                        SELECT DISTINCT q.id
                        FROM question_question as q
                        JOIN  subcategory_subcategory as sub
                        ON q.subcategory_id=sub.id
                        JOIN category_category as ca
                        ON sub.category_id=ca.id
                        WHERE sub.name='Fumador Activo'
                        AND ca.name='Factores Socioculturales'
                        AND q.code='B'
                           
                           
                           )
                           

                        
                           
                        
                        
                           
""",co)

In [2]:
question_tab=pd.read_sql("""
SELECT * FROM question_question as q
WHERE  (q.question_type='matrix_child' OR q.question_type='unique_response')
""",co)

In [3]:
question_tab

,id,code,question_type,description,parent_question_id,subcategory_id,is_required,position,input_type
0,1,A,unique_response,¿Número de personas aproximado que se observar...,NaN,1,1,1.0,NUM
1,3,B.2,matrix_child,Hombre,2.0,1,1,2.0,NUM
2,4,B.1,matrix_child,Mujer,2.0,1,1,1.0,NUM
3,6,C.1,matrix_child,Mestizos,5.0,1,1,1.0,NUM
4,7,C.2,matrix_child,Indígena,5.0,1,1,2.0,NUM
...,...,...,...,...,...,...,...,...,...
138,199,I.5,matrix_child,agua,38.0,1,0,5.0,NUM
139,200,III.4,matrix_child,café,73.0,1,0,4.0,NUM
140,201,III.5,matrix_child,agua,73.0,1,0,5.0,NUM
141,203,A.6,matrix_child,salón,179.0,6,1,6.0,NUM
142,204,A.7,matrix_child,oficina,179.0,6,1,7.0,NUM

In [77]:
question_tab.sort_values('id')
question_tab.to_csv('questions_mc_ur.csv',index=False)

In [7]:
res_tab=pd.read_sql("""
SELECT * FROM response_response as r
JOIN visit_visit as v
ON r.visita_id=v.id
JOIN surveysession_surveysession as ss
ON v.surveysession_id= ss.id
JOIN observer_observer as ob
ON ss.observer_id=ob.id
WHERE ob.email="andresuv.ortega@gmail.com"

""",co)

In [8]:
res_tab

,id,numeric_value,text_value,option_id,question_id,visita_id,id,visit_number,visit_start_date_time,visit_end_date_time,...,observational_distance,visit_number,state,observer_id,survey_id,zone_id,id,name,email,register_date
0,4091,2.0,None,3.0,1,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
1,4092,3.0,None,4.0,3,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
2,4093,1.0,None,2.0,4,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
3,4094,3.0,None,4.0,6,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
4,4095,5.0,None,6.0,7,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,4160,2.0,None,3.0,199,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
139,4161,3.0,None,4.0,200,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
140,4162,4.0,None,5.0,201,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
141,4232,1.0,None,2.0,203,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834
142,4233,1.0,None,2.0,204,123,123,1,2026-03-02 19:19:39.827423,2026-03-02 19:23:02.533814,...,111,1,2,15,1,6,15,andres david,andresuv.ortega@gmail.com,2026-03-02 19:19:09.182834

In [3]:
database_schema= pd.read_sql("""
SELECT 
    TABLE_NAME, 
    COLUMN_NAME, 
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH, 
    IS_NULLABLE, 
    COLUMN_DEFAULT, 
    COLUMN_KEY, 
    EXTRA
FROM 
    information_schema.columns
WHERE 
    table_schema = 'pocucdb'
ORDER BY 
    table_name, 
    ordinal_position;
""",co)

In [ ]:
q_r_schema=database_schema[(database_schema['TABLE_NAME']=='question_question') | (database_schema['TABLE_NAME']=='response_response')]

In [ ]:
q_r_schema.to_csv(os.path.join(os.getcwd(), 'q_r_schema.csv'), index=False)

In [4]:
questions=pd.read_sql("""
SELECT * FROM question_question;
""",co)

questions.to_csv('questions.csv',index=False)

In [83]:
questions_not_in_res=pd.read_sql("""
SELECT * FROM question_question as q
WHERE q.question_type IN ('unique_response', 'matrix_child')
AND q.id NOT IN (
    SELECT r.question_id
    FROM response_response as r 
    
)


""",co)

questions_not_in_res

Empty DataFrame
Columns: [id, code, question_type, description, parent_question_id, subcategory_id, is_required, position, input_type]
Index: []

In [9]:
res_total=pd.read_sql("""
SELECT DISTINCT r.id FROM response_response as r
""",co)

res_total

       id
0    3948
1    4091
2    3949
3    4092
4    3950
..    ...
281  4162
282  4089
283  4232
284  4090
285  4233

[286 rows x 1 columns]